// <auto-generated />
using System;
using DataWeb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataWeb.Migrations
{
    [DbContext(typeof(DataWebDbContext))]
    partial class DataWebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataWeb.Domain.Entities.DataJudJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("OriginalFileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("ProcessosProcessados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ResultFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("ResultFileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("pendente");

                    b.Property<int>("TotalProcessos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_DataJudJobs_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DataJudJobs_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_DataJudJobs_UserId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_DataJudJobs_UserId_CreatedAt");

                    b.ToTable("DataJudJobs", (string)null);
                });

            modelBuilder.Entity("DataWeb.Domain.Entities.DataJudJobProcesso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CodigoTribunal")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("NomeTribunal")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NumeroCNJ")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("pendente");

                    b.Property<int?>("TotalMovimentacoes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_DataJudJobProcessos_JobId");

                    b.HasIndex("NumeroCNJ")
                        .HasDatabaseName("IX_DataJudJobProcessos_NumeroCNJ");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DataJudJobProcessos_Status");

                    b.ToTable("DataJudJobProcessos", (string)null);
                });

            modelBuilder.Entity("DataWeb.Domain.Entities.DataJudJobProcesso", b =>
                {
                    b.HasOne("DataWeb.Domain.Entities.DataJudJob", "Job")
                        .WithMany("Processos")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DataWeb.Domain.Entities.DataJudJob", b =>
                {
                    b.Navigation("Processos");
                });
#pragma warning restore 612, 618
        }
    }
}
