services:
  dataweb-api:
    container_name: infra-dataweb-api
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "5267:5267"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5267
    restart: unless-stopped
