namespace DataWeb.Url;

public static class UrlEndpoints
{
    public static readonly Dictionary<string, string> PorEstado = new(StringComparer.Ordinal)
    {
        ["Acre"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjac/_search",
        ["Alagoas"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjal/_search",
        ["Amapá"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjap/_search",
        ["Amazonas"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjam/_search",
        ["Bahia"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjba/_search",
        ["Ceará"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjce/_search",
        ["Distrito Federal"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjdft/_search",
        ["Espírito Santo"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjes/_search",
        ["Goiás"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjgo/_search",
        ["Maranhão"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjma/_search",
        ["Mato Grosso"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjmt/_search",
        ["Mato Grosso do Sul"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjms/_search",
        ["Minas Gerais"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjmg/_search",
        ["Pará"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjpa/_search",
        ["Paraíba"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjpb/_search",
        ["Paraná"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjpr/_search",
        ["Pernambuco"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjpe/_search",
        ["Piauí"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjpi/_search",
        ["Rio de Janeiro"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjrj/_search",
        ["Rio Grande do Norte"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjrn/_search",
        ["Rio Grande do Sul"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjrs/_search",
        ["Rondônia"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjro/_search",
        ["Roraima"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjrr/_search",
        ["Santa Catarina"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjsc/_search",
        ["São Paulo"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt2/_search",
        ["Tocantins"] = "https://api-publica.datajud.cnj.jus.br/api_publica_tjto/_search",
        ["Trabalhista Rio De Janeiro"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt1/_search",
        ["Trabalhista São Paulo"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt2/_search",
        ["Trabalhista Minas Gerais"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt3/_search",
        ["Trabalhista Rio Grande Do Sul"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt4/_search",
        ["Trabalhista Bahia"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt5/_search",
        ["Trabalhista Pernambuco"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt6/_search",
        ["Trabalhista Ceará"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt7/_search",
        ["Trabalhista Amapá/Pará"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt8/_search",
        ["Trabalhista Paraná"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt9/_search",
        ["Trabalhista Tocantins / Distrito Federal"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt10/_search",
        ["Trabalhista Amazonas / Roraima"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt11/_search",
        ["Trabalhista Santa Catarina"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt12/_search",
        ["Trabalhista Paraíba"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt13/_search",
        ["Trabalhista Acre/Rondônia"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt14/_search",
        ["Trabalhista Maranhão"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt16/_search",
        ["Trabalhista São Paulo_2"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt15/_search",
        ["Trabalhista Espírito Santo"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt17/_search",
        ["Trabalhista Goiás"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt18/_search",
        ["Trabalhista Alagoas"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt19/_search",
        ["Trabalhista Sergipe"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt20/_search",
        ["Trabalhista Rio Grande do Norte"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt21/_search",
        ["Trabalhista Piauí"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trt23/_search",
        ["Federal 1ª Região"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trf1/_search",
        ["Federal 2ª Região"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trf2/_search",
        ["Federal 3ª Região"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trf3/_search",
        ["Federal 4ª Região"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trf4/_search",
        ["Federal 5ª Região"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trf5/_search",
        ["Federal 6ª Região"] = "https://api-publica.datajud.cnj.jus.br/api_publica_trf6/_search",

    };
}
