namespace DataWeb.Domain;

public static class CnjMaps
{
    public static readonly Dictionary<string, string> CodigoEstado = new(StringComparer.Ordinal)
    {
        ["8.01"] = "Acre",
        ["8.02"] = "Alagoas",
        ["8.03"] = "Amapá",
        ["8.04"] = "Amazonas",
        ["8.05"] = "Bahia",
        ["8.06"] = "Ceará",
        ["8.07"] = "Distrito Federal",
        ["8.08"] = "Espírito Santo",
        ["8.09"] = "Goiás",
        ["8.10"] = "Maranhão",
        ["8.11"] = "Mato Grosso",
        ["8.12"] = "Mato Grosso do Sul",
        ["8.13"] = "Minas Gerais",
        ["8.14"] = "Pará",
        ["8.15"] = "Paraíba",
        ["8.16"] = "Paraná",
        ["8.17"] = "Pernambuco",
        ["8.18"] = "Piauí",
        ["8.19"] = "Rio de Janeiro",
        ["8.20"] = "Rio Grande do Norte",
        ["8.21"] = "Rio Grande do Sul",
        ["8.22"] = "Rondônia",
        ["8.23"] = "Roraima",
        ["8.24"] = "Santa Catarina",
        ["8.25"] = "Sergipe",
        ["8.26"] = "São Paulo",
        ["8.27"] = "Tocantins",
        ["5.01"] = "Trabalhista Rio de Janeiro",
        ["5.02"] = "Trabalhista São Paulo",
        ["5.03"] = "Trabalhista Minas Gerais",
        ["5.04"] = "Trabalhista Rio Grande Do Sul",
        ["5.05"] = "Trabalhista Bahia",
        ["5.06"] = "Trabalhista Pernambuco",
        ["5.07"] = "Trabalhista Ceará",
        ["5.08"] = "Trabalhista Amapá/Pará",
        ["5.09"] = "Trabalhista Paraná",
        ["5.10"] = "Trabalhista Tocantins / Distrito Federal",
        ["5.11"] = "Trabalhista Amazonas / Roraima",
        ["5.12"] = "Trabalhista Santa Catarina",
        ["5.13"] = "Trabalhista Paraíba",
        ["5.14"] = "Trabalhista Acre / Rondônia",
        ["5.15"] = "Trabalhista São Paulo_2",
        ["5.16"] = "Trabalhista Maranhão",
        ["5.17"] = "Trabalhista Espírito Santo",
        ["5.18"] = "Trabalhista Goiás",
        ["5.19"] = "Trabalhista Alagoas",
        ["5.20"] = "Trabalhista Sergipe",
        ["5.21"] = "Trabalhista Rio Grande do Norte",
        ["5.22"] = "Trabalhista Piauí",
        ["4.01"] = "Federal 1ª Região",
        ["4.02"] = "Federal 2ª Região",
        ["4.03"] = "Federal 3ª Região",
        ["4.04"] = "Federal 4ª Região",
        ["4.05"] = "Federal 5ª Região",
        ["4.06"] = "Federal 6ª Região",

    };
}